### ISSUE TITLE
Does not work on Mac OS (SocketException)

### ISSUE THREAD

**Issue by Mimi8298** [Cysharp/AlterNats#23]
Hello, I just tried your library on a simple test program, but it does not seem to work on Mac OS. 
TcpConnection seems to set SendBufferSize to 0, which throws a SocketException on Mac OS.

Here is the stacktrace :
```
System.Net.Sockets.SocketException (22): Invalid argument
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.SetSocketOption(SocketOptionLevel optionLevel, SocketOptionName optionName, Int32 optionValue, Boolean silent)
   at System.Net.Sockets.Socket.SetSocketOption(SocketOptionLevel optionLevel, SocketOptionName optionName, Int32 optionValue)
   at System.Net.Sockets.Socket.set_SendBufferSize(Int32 value)
   at AlterNats.Internal.TcpConnection..ctor()
   at AlterNats.NatsConnection.InitialConnectAsync()
```

**Comment by neuecc** [comment]
thanks for reporting, I'll check soon.

**Comment by neuecc** [comment]
https://github.com/dotnet/corefx/pull/17853#issuecomment-291371266

> OSX doesn't support setting the buffer size to 0. Windows and Linux do. So the OSX behavior is going to be different if you try to set the buffer size to 0 -- either it's an error, or it gets mapped to something else (like a very small buffer size) or ... something else, maybe? Making this an error seems like the best option to me.

I'll add platform check like  `if (!RuntimeInformation.IsOSPlatform(OSPlatform.OSX))`

**Comment by Mimi8298** [comment]
Ok thank you.
Is there any useful reason to set the buffer sizes to 0?
From what i seen, even if on linux it doesn't throw an error, linux ignores the setting to 0 (they made a max of the value to the SOCK_MIN_SNDBUF value).
I put the link where i saw that : [https://stackoverflow.com/questions/67113706/why-does-setting-so-sndbuf-and-so-rcvbuf-destroy-performance](url)
